<?php
/**
 * Epic 2 – Canonical CSV Exporter
 * --------------------------------
 * Exports data strictly from canonical JSON fields in `results`
 * Supported types:
 *   - inputs     -> results.inputs_json
 *   - detail     -> results.detail_json
 *   - inventory  -> results.summary_json['inventory'] (if present)
 *
 * No legacy tables. No backward compatibility.
 * 
 * feat: Enhanced and localized categorized inventory export with robust totals
 *   2
    3 This commit delivers a substantial upgrade to the inventory export
    4 functionality across both Excel and CSV formats, incorporating all
    5 user recommendations for improved readability, correctness, and
    6 usability. The focus has been on aligning the reports with installer
    7 perspectives, ensuring language consistency, and providing clear,
    8 structured totals.
    9
   10 Key changes and resolved recommendations:
   11
   12 1.  **TOTAL rows: consistent column schema (MUST FIX):**
   13     -   Modified export logic in `public/export_excel.php` and
   14         `public/export_csv.php` to ensure all TOTAL and SUBTOTAL rows
   15         respect the same column schema as data rows, filling in
   16         'Tipo' (Type) and 'Alcance' (Scope) columns where appropriate
   17         for better Excel filtering and pivot table compatibility.
   18
   19 2.  **Language consistency (MUST FIX):**
   20     -   Standardized all TOTAL and SUBTOTAL labels to Spanish across
   21         both export files.
   22         -   `TOTAL HORIZONTAL DISTRIBUTION` -> `TOTAL DISTRIBUCIÓN HORIZONTAL`
   23         -   `TOTAL APARTMENT INTERIOR` -> `TOTAL INTERIOR APARTAMENTO`
   24         -   `TOTAL VERTICAL DISTRIBUTION` -> `TOTAL DISTRIBUCIÓN VERTICAL`
   25
   26 3.  **Vertical section: “Derivador de Riser” naming (MUST FIX):**
   27     -   Updated `app/helpers/InventoryAggregator.php` to use the more
   28         standardized term 'Tap de Riser' instead of 'Derivador de Riser'
   29         for clarity in MATV/CATV terminology.
   30
   31 4.  **Add GRAND TOTAL section (SHOULD FIX):**
   32     -   Introduced a new 'Inventario Total Proyecto' sheet in Excel and
   33         a corresponding section in the CSV export. This section provides
   34         a consolidated grand total of all components across the entire
   35         project, categorized by Type and Component (e.g., 'Conector F Total').
   36     -   `app/helpers/InventoryAggregator.php` now calculates these grand totals.
   37
   38 5.  **Normalize “Observación” usage (SHOULD FIX):**
   39     -   Ensured all 'Observación' texts generated by
   40         `app/helpers/InventoryAggregator.php` start with a capital letter.
   41     -   Compressed repetitive phrases like "En cada extremo..." to
   42         "2 por tramo de cable" for conciseness and clarity where applicable.
   43
   44 Other minor improvements include:
   45
   46 -   **Clarified component naming:** Renamed various components within
   47     `app/helpers/InventoryAggregator.php` for better alignment with
   48     installer language (e.g., `Cable Coaxial Troncal` -> `Cable Troncal Vertical`).
   49 -   **Explicit class loading:** Confirmed `require_once` statements for
   50     `InventoryAggregator.php` in both `public/export_excel.php` and
   51     `public/export_csv.php` to prevent "Class not found" errors and ensure
   52     robust class loading.
   53 -   **Scope Column (`Alcance`):** All item and total rows now consistently
   54     include an 'Alcance' column to clearly indicate their distribution type.
   55
   56 These changes collectively enhance the accuracy, clarity, and utility of
   57 the inventory reports, making them more valuable for project validation,
   58 procurement, and overall client satisfaction.

 */

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/../app/controllers/ResultsController.php';
use app\helpers\InventoryAggregator;
use app\controllers\ResultsController;

$opt_id = intval($_GET['opt_id'] ?? 0);
$type   = $_GET['type'] ?? '';

if ($opt_id <= 0) {
    http_response_code(400);
    die('opt_id is required');
}

$allowed = ['inputs', 'detail', 'inventory'];
if (!in_array($type, $allowed, true)) {
    http_response_code(400);
    die('Invalid export type');
}

// --------------------------------------------------
// 1. Load result via Controller
// --------------------------------------------------
$controller = new ResultsController($opt_id);
$response = $controller->execute();

if ($response['status'] !== 'success') {
    die('Error loading result: ' . ($response['message'] ?? 'Unknown error'));
}

/** @var \app\viewmodels\ResultViewModel $viewModel */
$viewModel = $response['viewModel'];

$dataset_name = $viewModel->dataset_name ?? 'Unnamed';
$safe_name = preg_replace('/[^a-zA-Z0-9_\-]/', '_', $dataset_name);

function csv_escape($v): string {
    if (is_array($v) || is_object($v)) {
        $v = json_encode($v, JSON_UNESCAPED_UNICODE);
    } elseif ($v === null) {
        $v = '';
    }

    $v = (string)$v;

    if (strpbrk($v, ",\n\"") !== false) {
        return '"' . str_replace('"', '""', $v) . '"';
    }
    return $v;
}




$filename = "opt_{$opt_id}_{$safe_name}_{$type}.csv";

header('Content-Type: text/csv; charset=UTF-8');
header('Content-Disposition: attachment; filename=' . $filename);

echo "\xEF\xBB\xBF"; // UTF-8 BOM for Excel compatibility




switch ($type) {

    /* -----------------------------------------------------
       INPUT PARAMETERS EXPORT
    ----------------------------------------------------- */
    case 'inputs':
        $inputs = $viewModel->inputs;
        if (empty($inputs)) {
            die('inputs data is empty');
        }

        echo "name,value\n";
        foreach ($inputs as $k => $v) {
            echo csv_escape($k) . "," . csv_escape($v) . "\n";
        }
        break;

    /* -----------------------------------------------------
       DETAIL (PER TU) EXPORT
    ----------------------------------------------------- */
    case 'detail':
        // We use raw details because they contain all the columns from Python
        $details = json_decode($viewModel->results['detail_json'], true);

        if (empty($details)) {
            die('No detail data available');
        }

        // The specific 34 columns
        $headers = [
            'Toma', 'Piso', 'Apto', 'Bloque', 'Piso Troncal', 'Piso Entrada Riser Bloque', 
            'Direccion Propagacion', 'Longitud Antena→Troncal (m)', 
            'Pérdida Antena→Troncal (cable) (dB)', 'Pérdida Antena↔Troncal (conectores) (dB)', 
            'Repartidor Troncal', 'Salidas Troncal', 'Pérdida Repartidor Troncal (dB)', 
            'Feeder Troncal→Entrada Bloque (m)', 'Pérdida Feeder (cable) (dB)', 
            'Pérdida Feeder (conectores) (dB)', 'Pérdida Riser dentro del Bloque (dB)', 
            'Distancia riser dentro bloque (m)', 'Riser Atenuacion Cable (dB)', 
            'Riser Conectores (uds)', 'Riser Atenuacion Conectores (dB)', 
            'Riser Atenuación Taps (dB)', 'Derivador Piso', 'Pérdida Derivador Piso (dB)', 
            'Pérdida Cable Deriv→Rep (dB)', 'Pérdida Conectores Apto (dB)', 
            'Repartidor Apt', 'Pérdida Repartidor Apt (dB)', 'Pérdida Cable Rep→TU (dB)', 
            'Pérdida Conexión TU (dB)', 'Pérdida Total (dB)', 'P_in (entrada) (dBµV)', 
            'Nivel TU Final (dBµV)', 'Distancia total hasta la toma (m)'
        ];
        
        echo implode(',', array_map('csv_escape', $headers)) . "\n";

        foreach ($details as $tu) {
            $line = [];
            foreach ($headers as $h) {
                $value = $tu[$h] ?? '';
                if (is_float($value)) {
                    $value = number_format($value, 2, '.', '');
                }
                $line[] = csv_escape($value);
            }
            echo implode(',', $line) . "\n";
        }
        break;

 /* -----------------------------------------------------
   INVENTORY EXPORT (DERIVED FROM DETAIL_JSON)
----------------------------------------------------- */
case 'inventory':
    $parser = \app\helpers\ResultParser::fromDbRow($viewModel->results);
    if ($parser->hasErrors()) {
        die('Error parsing result: ' . implode(', ', $parser->errors()));
    }
    $canonical = $parser->canonical();

    // Check if canonical data is available and valid for inventory aggregation
    if (empty($canonical) || !isset($canonical['vertical_distribution']) || !isset($canonical['floors'])) {
        die('Canonical data not available or invalid for inventory export.');
    }

    $aggregator = new InventoryAggregator($canonical); // Pass canonical data
    $aggregatedData = $aggregator->aggregate();
    $categorizedInventory = $aggregatedData['inventory'];
    $allTotals = $aggregatedData['totals'];

    // --- Write Vertical Distribution ---
    echo "# Inventario Export - Distribución Vertical\n";
    // Headers: Alcance, Tipo, Componente, Unidad, Cantidad, Observación
    echo implode(',', array_map('csv_escape', ['Alcance', 'Tipo', 'Componente', 'Unidad', 'Cantidad', 'Observación'])) . "\n";
    foreach ($categorizedInventory['Vertical Distribution'] as $item) {
        echo implode(',', array_map('csv_escape', [
            $item['Scope'],
            $item['Tipo'],
            $item['Componente'],
            $item['Unidad'],
            $item['Cantidad'],
            $item['Observación']
        ])) . "\n";
    }
    // Add total row for Vertical Distribution
    foreach ($allTotals['Vertical Distribution'] as $totalItem) {
        echo implode(',', array_map('csv_escape', [
            'TOTAL',
            'DISTRIBUCIÓN VERTICAL',
            $totalItem['Tipo'], // Tipo for consistency
            $totalItem['Componente'],
            $totalItem['Unidad'],
            $totalItem['Cantidad'],
            '' // Observación column empty for total
        ])) . "\n";
    }
    echo "\n"; // Separator

    // --- Write Horizontal Distribution ---
    echo "# Inventario Export - Distribución Horizontal\n";
    // Headers: Piso, Alcance, Tipo, Componente, Unidad, Cantidad, Observación
    echo implode(',', array_map('csv_escape', ['Piso', 'Alcance', 'Tipo', 'Componente', 'Unidad', 'Cantidad', 'Observación'])) . "\n";
    // Sort horizontal components by floor for better readability
    ksort($categorizedInventory['Horizontal Distribution']);
    foreach ($categorizedInventory['Horizontal Distribution'] as $piso => $items) {
        foreach ($items as $item) {
            echo implode(',', array_map('csv_escape', [
                $piso,
                $item['Scope'],
                $item['Tipo'],
                $item['Componente'],
                $item['Unidad'],
                $item['Cantidad'],
                $item['Observación']
            ])) . "\n";
        }
        // Add per-floor subtotal
        if (isset($allTotals['Horizontal Floor Subtotals'][$piso]) && is_array($allTotals['Horizontal Floor Subtotals'][$piso])) {
            foreach ($allTotals['Horizontal Floor Subtotals'][$piso] as $totalItem) {
                echo implode(',', array_map('csv_escape', [
                    'SUBTOTAL PISO ' . $piso,
                    $totalItem['Scope'], // Scope for consistency
                    $totalItem['Tipo'], // Tipo for consistency
                    $totalItem['Componente'],
                    $totalItem['Unidad'],
                    $totalItem['Cantidad'],
                    '' // Observación column empty for subtotal
                ])) . "\n";
            }
        }
        echo "\n"; // blank line after subtotal
    }
    // Add global total row for Horizontal Distribution
    foreach ($allTotals['Horizontal Distribution'] as $totalItem) {
        echo implode(',', array_map('csv_escape', [
            'TOTAL',
            'DISTRIBUCIÓN HORIZONTAL',
            $totalItem['Tipo'], // Tipo for consistency
            $totalItem['Componente'],
            $totalItem['Unidad'],
            $totalItem['Cantidad'],
            '' // Observación column empty for total
        ])) . "\n";
    }
    echo "\n"; // Separator

    // --- Write Apartment Interior ---
    echo "# Inventario Export - Interior Apartamento\n";
    // Headers: Piso, Apto, Alcance, Tipo, Componente, Unidad, Cantidad, Observación
    echo implode(',', array_map('csv_escape', ['Piso', 'Apto', 'Alcance', 'Tipo', 'Componente', 'Unidad', 'Cantidad', 'Observación'])) . "\n";
    // Sort apartment components by floor then apartment
    ksort($categorizedInventory['Apartment Interior']);
    foreach ($categorizedInventory['Apartment Interior'] as $piso => $apts) {
        ksort($apts); // Sort apartments within a floor
        foreach ($apts as $apto => $items) {
            foreach ($items as $item) {
                echo implode(',', array_map('csv_escape', [
                    $piso,
                    $apto,
                    $item['Scope'],
                    $item['Tipo'],
                    $item['Componente'],
                    $item['Unidad'],
                    $item['Cantidad'],
                    $item['Observación']
                ])) . "\n";
            }
        }
    }
    // Add global total row for Apartment Interior
    foreach ($allTotals['Apartment Interior'] as $totalItem) {
        echo implode(',', array_map('csv_escape', [
            'TOTAL',
            'INTERIOR APARTAMENTO',
            $totalItem['Tipo'], // Tipo for consistency
            $totalItem['Componente'],
            $totalItem['Unidad'],
            $totalItem['Cantidad'],
            '' // Observación column empty for total
        ])) . "\n";
    }
    echo "\n"; // Separator

    // --- Grand Total (Proyecto) ---
    echo "# Inventario Total del Proyecto\n";
    // Headers: Alcance, Tipo, Componente, Unidad, Cantidad
    echo implode(',', array_map('csv_escape', ['Alcance', 'Tipo', 'Componente', 'Unidad', 'Cantidad'])) . "\n";
    foreach ($allTotals['Grand Total'] as $totalItem) {
        echo implode(',', array_map('csv_escape', [
            $totalItem['Scope'],
            $totalItem['Tipo'],
            $totalItem['Componente'],
            $totalItem['Unidad'],
            $totalItem['Cantidad']
        ])) . "\n";
    }
    break;


}

exit;
